tutorial_directory/.ipynb_checkpoints/example_markdown-checkpoint.md
tutorial_directory/example_markdown.md

This pull request has some small changes to the tutorial markdown example, that adds content for the different type of headings that are available.

Small changes to the contribution markdown file

---

individual_modules/python_for_data_analysis/Python_NumPy.ipynb

Minor change - lesson aims

---

individual_modules/intermediate_version_control/basic_git.ipynb
individual_modules/intermediate_version_control/config_git.ipynb

Add link to git config online documentation.

Fix broken link in intermediate git

---

where_is_my_understanding/quizes/intro_to_hpc.json

Hi folks - just having a play with the quizzes and noticed some typos/errors on the HPC one. Hopefully useful but feel free to ignore if not!

Fixing HPC quiz typos

---

where_is_my_understanding/quizes/intro_to_r.json
where_is_my_understanding/quizes/regression_analysis_with_R.json
where_is_my_understanding/quizes/working_with_data_in_r.json

Mainly typos and some changes to questions to test understanding of code

Making basic changes to the quiz files 

---

.github/workflows/deploy.yml

Refactored Github Action to not upload when checking jupyter book can be built in PR.

Seperate out building and deploying of juypter book in github action

---

_config.yml
requirements.txt

Updated requirements.txt with rpy2 package

---

data/accepting_applications.csv
programme_information/R.ipynb
programme_information/advanced_regression_analysis_with_r.ipynb
programme_information/computational_thinking.ipynb
programme_information/computational_thinking_overview.ipynb
programme_information/high_performance_computing.ipynb
programme_information/intermediate_version_control.ipynb
programme_information/intro_to_hpc.ipynb
programme_information/intro_to_julia.ipynb
programme_information/intro_to_python.ipynb
programme_information/intro_to_r.ipynb
programme_information/intro_to_unix.ipynb
programme_information/intro_to_version_control.ipynb
programme_information/julia.ipynb
programme_information/programme_information.ipynb
programme_information/python.ipynb
programme_information/python_for_data_analysis.ipynb
programme_information/regression_analysis_with_r.ipynb
programme_information/software_development.ipynb
programme_information/software_development_best_practices.ipynb
programme_information/unix.ipynb
programme_information/version_control.ipynb
programme_information/working_with_data_in_r.ipynb

Add python code to generate markdown code for courses 

---

.github/workflows/deploy-book.yml

update the github action to use cron job

---

_toc.yml
cfrr_program_details/coding_languages_self_study.ipynb
cfrr_program_details/coding_practices_self_study.ipynb
programme_information/coding_languages.ipynb
programme_information/coding_practices.ipynb

Requirement for the website to be restructured as: 
Coding Languages- Julia, Python, R, Unix
Coding Practices- Computational Thinking, HPC, Machine Learning, Parallel Computing, Software Development, Version Control.

Refactor website for coding languages and coding practices

---

_toc.yml
where_is_my_understanding/coding_languages_quiz.ipynb
where_is_my_understanding/coding_practices_quiz.ipynb

Website refactor for the where is my understanding quizes based on the split of coding languages and coding practices.

Website refactor for quizes

---

programme_information/working_with_data_in_r.ipynb

Update working with data R version from 4.1 to 4.3 based on handouts

---

where_is_my_understanding/quizes/numpy_course_skip_quiz.json
where_is_my_understanding/quizes/pandas_course_skip_quiz.json

Two minor typos while reviewing :
- `np.linspace`
- consistency with "DataFrame" and "df" without quotes.

Minor quiz typos

---

data/previous_workshops.csv
data/workshop_info.csv

Updated past course information and Term 2 timetable

Course Dates

---

course_homepages/R.ipynb
course_homepages/computational_thinking.ipynb
course_homepages/high_performance_computing.ipynb
course_homepages/julia.ipynb
course_homepages/python.ipynb
course_homepages/software_development.ipynb
course_homepages/unix.ipynb
course_homepages/version_control.ipynb
individual_modules/section_landing_pages/parallel_computing.md
individual_modules/section_landing_pages/software_development_best_practice.md
where_is_my_understanding/R.ipynb
where_is_my_understanding/computational_thinking_overview.ipynb
where_is_my_understanding/high_performance_computing.ipynb
where_is_my_understanding/julia.ipynb
where_is_my_understanding/python.ipynb
where_is_my_understanding/software_development.ipynb
where_is_my_understanding/unix.ipynb
where_is_my_understanding/version_control.ipynb

Improve landing pages with summarises and links to content 

---

individual_modules/improve_your_r_code/data_table.ipynb
individual_modules/improve_your_r_code/microbenchmark.ipynb
individual_modules/improve_your_r_code/parallelisation.ipynb
individual_modules/improve_your_r_code/rcpp.ipynb
individual_modules/improve_your_r_code/style.ipynb
individual_modules/improve_your_r_code/vectorisation.ipynb
individual_modules/section_landing_pages/improve_your_r_code.md
programme_information/improve_your_r_code.ipynb

Removed the blocks importing the required R packages and the %load_ext rpy2.ipython command at the start of each notebook as this looked untidy on the website.

fix typos and tidy printing at the start of each notebook

---

individual_modules/section_landing_pages/markdown_with_python.md

I've separated the installation and pre-requisite knowledge in line with Anne's suggestion on the markdown with python landpage

landpage update

---

individual_modules/markdown_with_python/3-Markdown-Fundamentals.md
individual_modules/markdown_with_python/4-Markdown-Task-1.md
individual_modules/markdown_with_python/5-How-to-embed-Python-Code-in-Markdown.md
individual_modules/markdown_with_python/8-Further-Knowledge.md

Some minor corrections through the document.

Using markdown for python update

---

individual_modules/markdown_with_python/3-Markdown-Fundamentals.md

@liamjberrisford a couple more updates

Minor updates

---

.github/workflows/accessibility.yml
home_page.md
pa11yci.js
package.json
where_is_my_understanding/computational_thinking.ipynb

This PR will add the functionality for an automatic process of accessibility assessment for the generated .html files for the website. 
The new GitHub Action can be tested locally with`act pull_request --container-architecture linux/amd64`

[WIP] Accessibility Assessment CI with Pa11y

---

programme_information/R.ipynb

TYPO: Programme Info R four to seven
